# Generated by Django 5.1.7 on 2025-04-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100, unique=True)),
                ("gpid", models.CharField(max_length=20, unique=True)),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("Green", "Green"),
                            ("Blue", "Blue"),
                            ("Red", "Red"),
                            ("Yellow", "Yellow"),
                        ],
                        default="Green",
                        max_length=10,
                    ),
                ),
                (
                    "line",
                    models.CharField(
                        choices=[
                            ("1", "Line\xa01"),
                            ("2", "Line\xa02"),
                            ("3", "Line\xa03"),
                            ("4", "Line\xa04"),
                            ("MOH", "MOH"),
                            ("ALL", "ALL"),
                        ],
                        default="1",
                        help_text="Which line (or MOH/ALL) the employee normally works",
                        max_length=10,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
