# Generated by Django 5.1.7 on 2025-04-25 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_remove_employee_user"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="E.g. 'Forklift', 'Slicing', 'Seasoning'",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Who this skill record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_profile",
                        to="employees.employee",
                    ),
                ),
                (
                    "additional_skills",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Any other skills this person has",
                        related_name="additional_for",
                        to="skills.skillmaster",
                    ),
                ),
                (
                    "primary_skill",
                    models.ForeignKey(
                        help_text="Their main skill",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_for",
                        to="skills.skillmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Skill Matrix",
                "verbose_name_plural": "Employee Skill Matrices",
                "unique_together": {("employee", "primary_skill")},
            },
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
