# Generated by Django 5.1.7 on 2025-04-28 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0004_remove_employee_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "team",
                    models.CharField(
                        choices=[
                            ("Red", "Red Shift"),
                            ("Green", "Green Shift"),
                            ("Blue", "Blue Shift"),
                            ("Yellow", "Yellow Shift"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "shift_time",
                    models.CharField(
                        choices=[("Day", "Day Shift"), ("Night", "Night Shift")],
                        max_length=6,
                    ),
                ),
            ],
            options={
                "ordering": ["date", "team", "shift_time"],
                "unique_together": {("date", "team", "shift_time")},
            },
        ),
        migrations.CreateModel(
            name="ShiftHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="employees.employee",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="shifts.shift",
                    ),
                ),
            ],
            options={
                "ordering": ["shift", "employee"],
                "unique_together": {("shift", "employee")},
            },
        ),
    ]
