# Generated by Django 5.1.7 on 2025-04-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("GSO", "General Support Operator"),
                    ("GO", "General Operator"),
                    ("MT", "Manufacturing Technician"),
                    ("ST", "Shift Technician"),
                ],
                default="GSO",
                help_text="What type of role this person performs",
                max_length=3,
            ),
        ),
    ]
