# Generated by Django 5.1.7 on 2025-04-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="user",
        ),
    ]
